project_id = "unawxvbbievblwkdttzi"

[functions.create-payment]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.get-checkout-session]
verify_jwt = false

[functions.get-stripe-publishable-key]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.resend-missing-emails]
verify_jwt = false
